INSERT INTO rms.Areas VALUES (1, 'Hong Kong');
INSERT INTO rms.Areas VALUES (2, 'Kowloon');
INSERT INTO rms.Areas VALUES (3, 'New Territories');
INSERT INTO rms.Areas VALUES (4, 'Outlying Islands');

INSERT INTO rms.Districts (Name, AreaID) VALUES ('Aberdeen', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Admiralty', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Ap Lei Chau', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Causeway Bay', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Central', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Chai Wan', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Cyberport', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Deep Water Bay', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Happy Valley', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Heng Fa Chuen', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Lan Kwai Fong', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Mid-Levels', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('North Point', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Pok Fu Lam', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Quarry Bay', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Repulse Bay', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Sai Wan Ho', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Shau Kei Wan', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Shek O', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Sheung Wan', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Soho', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Stanley', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tai Hang', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tai Koo', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('The Peak', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tin Hau', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Wan Chai', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Western Districts', 1);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Cheung Sha Wan', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Choi Hung', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Diamond Hill', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Ho Man Tin', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Hung Hom', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Jordan', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Knutsford Terrace', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Kowloon Bay', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Kowloon City', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Kowloon Tong', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Kwun Tong', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Lai Chi Kok', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Lam Tin', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Lei Yue Mun', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Lok Fu', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Mei Foo', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Mong Kok', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Ngau Tau Kwok', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Prince Edward', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('San Po Kong', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Sham Shui Po', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Shek Kip Mei', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tai Kok Tsui', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('To Kwa Wan', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tsim Sha Tsui', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tsz Wan Shan', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Wong Tai Sin', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Yau Ma Tei', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Yau Tong', 2);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Fanling', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Fo Tan', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Kwai Chung', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Kwai Fong', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Lau Fau shan', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Lo Wu', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Lok Ma Chau', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Ma On Shan', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Ma Wan', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Sai Kung', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Sha Tin', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Sham Tseng', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Sheung Shui', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tai Po', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tai Wai', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tai Wo', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tin Shui Wai', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tseung Kwan O', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tsing Yi', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tsuen Wan', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tuen Mun', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Yuen Long', 3);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Chek Lap Kok', 4);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Cheung Chau', 4);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Discovery Bay', 4);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Lamma Island', 4);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Lantau Island', 4);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Ping Chau', 4);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Po Toi Island', 4);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tai O', 4);
INSERT INTO rms.Districts (Name, AreaID) VALUES ('Tung Chung', 4);